name: StellarNetApp
version: '1.0-SNAPSHOT'
main: com.zvicraft.stellarNetApp.StellarNetApp
api-version: '1.21'
authors: [ zvicraft, zvielkoren ]
website: https://zviel.com
softdepend: ["PlaceholderAPI"]

commands:
  test:
    description: Testing command
    usage: /<command>
    permission: stellarnetapp.admin.test